# Generated by Django 4.2.4 on 2025-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="money",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
