# Generated by Django 4.2.4 on 2025-05-22 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kor_co_nm', models.CharField(max_length=255)),
                ('fin_prdt_nm', models.CharField(max_length=255)),
                ('join_way', models.CharField(max_length=255)),
                ('loan_type', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deposit_product', serialize=False, to='products.financialproduct')),
                ('fin_co_no', models.CharField(max_length=255)),
                ('dcls_month', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('intr_rate_type', models.CharField(max_length=255)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='loan_product', serialize=False, to='products.financialproduct')),
                ('fin_co_no', models.CharField(max_length=255)),
                ('dcls_month', models.CharField(max_length=10)),
                ('loan_inci_expn', models.TextField(blank=True, null=True)),
                ('erly_rpay_fee', models.TextField(blank=True, null=True)),
                ('dly_rate', models.TextField(blank=True, null=True)),
                ('loan_lmt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='saving_product', serialize=False, to='products.financialproduct')),
                ('fin_co_no', models.CharField(max_length=255)),
                ('dcls_month', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('intr_rate_type', models.CharField(max_length=255)),
                ('rsrv_type', models.CharField(max_length=100)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RequirementOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('save_trm', models.IntegerField()),
                ('intr_rate_type', models.CharField(max_length=255)),
                ('rsrv_type', models.CharField(blank=True, max_length=100, null=True)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_options', to='products.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='MortgageLoanOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mrtg_type', models.CharField(max_length=255)),
                ('rpay_type', models.CharField(max_length=255)),
                ('lend_rate_type', models.CharField(max_length=255)),
                ('lend_rate_min', models.FloatField()),
                ('lend_rate_max', models.FloatField()),
                ('lend_rate_avg', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_options', to='products.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct_JoinWay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('join_way', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_joinways', to='products.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='LendingRateOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rpay_type', models.CharField(max_length=255)),
                ('lend_rate_type', models.CharField(max_length=255)),
                ('lend_rate_min', models.FloatField()),
                ('lend_rate_max', models.FloatField()),
                ('lend_rate_avg', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_rate_options', to='products.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct_JoinWay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('join_way', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_joinways', to='products.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crdt_prdt_type', models.CharField(max_length=255)),
                ('crdt_lend_rate_type', models.CharField(max_length=255)),
                ('crdt_grad_1', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_grad_4', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_grad_5', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_grad_6', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_grad_10', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_grad_11', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_grad_12', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_grad_13', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_grad_avg', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_options', to='products.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='products.financialproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
