# Generated by Django 4.2.4 on 2025-05-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditloanoption',
            name='crdt_grad_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanoption',
            name='crdt_grad_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanoption',
            name='crdt_grad_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanoption',
            name='crdt_grad_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanoption',
            name='crdt_grad_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanoption',
            name='crdt_grad_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanoption',
            name='crdt_grad_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanoption',
            name='crdt_grad_6',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
